# Generated by Django 5.0.4 on 2024-04-22 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodeusers',
            name='invite_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invite_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitationcodeusers',
            name='main_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
